/*
 * Copyright(C) 2010-2012 Alibaba Group Holding Limited
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License version 2 as
 *  published by the Free Software Foundation.
 *
 */
package com.taobao.ad.easyschedule.dataobject;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;

import com.taobao.ad.easyschedule.base.PageInfo;

/**
 * CodeDO generated by hbm2java
 */
@Entity(name="es_code")
@IdClass(CodeKey.class)
public class CodeDO extends PageInfo implements java.io.Serializable {

	public static String CODE_KEY_JOB_GROUP = "JOB_GROUP";
	public static String CODE_KEY_HTTPJOB_JOBDATA = "HTTPJOB_JOBDATA";
	public static String CODE_KEY_SHELLJOB_JOBDATA = "SHELLJOB_JOBDATA";
	public static String CODE_KEY_LINECOUNTJOB_JOBDATA = "LINECOUNTJOB_JOBDATA";
	public static String CODE_KEY_DTJOB_JOBDATA = "DATATRACKINGJOB_JOBDATA";
	public static String CODE_KEY_HB_JOBDATA = "HEARTBEATJOB_JOBDATA";
    public static String CODE_KEY_PROCEDURE_JOBDATA = "STOREDPROCEDURE_JOBDATA";
    
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 键 KEY
	 */
	@Id
	private String codekey;
	/**
	 * 编码 KEYCODE
	 */
	@Id
	private String keycode;
	/**
	 * 名字 KEYNAME
	 */
	@Column(name="KEYNAME")
	private String keyname;
	/**
	 * 描述 KEYDESC
	 */
	@Column(name="KEYDESC")
	private String keydesc;
	/**
	 * 顺序号 SORTNUM
	 */
	@Column(name="SORTNUM")
	private Long sortnum;

 

	public String getCodekey() {
		return codekey;
	}

	public void setCodekey(String codekey) {
		this.codekey = codekey;
	}

	public String getKeycode() {
		return this.keycode;
	}

	public void setKeycode(String keycode) {
		this.keycode = keycode;
	}

	public String getKeyname() {
		return this.keyname;
	}

	public void setKeyname(String keyname) {
		this.keyname = keyname;
	}

	public String getKeydesc() {
		return this.keydesc;
	}

	public void setKeydesc(String keydesc) {
		this.keydesc = keydesc;
	}

	public Long getSortnum() {
		return this.sortnum;
	}

	public void setSortnum(Long sortnum) {
		this.sortnum = sortnum;
	}
	 
}
@Embeddable
class CodeKey implements java.io.Serializable{
	
	private static final long serialVersionUID = 1L;
	public CodeKey(){}
	 
	@Column(name="codekey")
	private String codekey;
	@Column(name="keycode")
	private String keycode;
 
	public String getCodekey() {
		return codekey;
	}
	public void setCodekey(String codekey) {
		this.codekey = codekey;
	}
	public String getKeycode() {
		return keycode;
	}
	public void setKeycode(String keycode) {
		this.keycode = keycode;
	}
	
	
}
