/*
 * Copyright(C) 2010-2012 Alibaba Group Holding Limited
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License version 2 as
 *  published by the Free Software Foundation.
 *
 */
package com.taobao.ad.easyschedule.dataobject;

import static com.taobao.ad.easyschedule.commons.utils.StringUtil.bSubstring;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import com.taobao.ad.easyschedule.base.PageInfo;

/**
 * ConfigDO generated by hbm2java
 */
@Entity(name = "es_config")
public class ConfigDO extends PageInfo implements java.io.Serializable {

	public static String CONFIG_KEY_INSTANCE_CONTROL_INTERFACE = "INSTANCE_CONTROL_INTERFACE";
	public static String CONFIG_KEY_es_TOP_NOTIFY = "es_TOP_NOTIFY";
	public static String CONFIG_KEY_es_TOP_NOTIFY_MSG = "es_TOP_NOTIFY_MSG";
	public static String CONFIG_KEY_JOB_DEFAULT_CRONEXPRESSION = "JOB_DEFAULT_CRONEXPRESSION";
	public static String CONFIG_KEY_JOB_DEFAULT_TRIGGERTYPE = "JOB_DEFAULT_TRIGGERTYPE";
	public static String CONFIG_KEY_JOB_DEFAULT_REPEATCOUNT = "JOB_DEFAULT_REPEATCOUNT";
	public static String CONFIG_KEY_JOB_DEFAULT_REPEATINTERVAL = "JOB_DEFAULT_REPEATINTERVAL";
	public static String CONFIG_KEY_JOB_DEFAULT_PRIORITY = "JOB_DEFAULT_PRIORITY";
	public static String CONFIG_KEY_JOB_DATATRACKINGLOG_NUMBER = "JOB_DATATRACKINGLOG_NUMBER";
	public static String CONFIG_KEY_JOB_DEFAULT_NOTIFY_WAITING_MSG = "JOB_DEFAULT_NOTIFY_WAITING_MSG";
	public static String CONFIG_KEY_JOB_DEFAULT_NOTIFY_FINISHED_MSG = "JOB_DEFAULT_NOTIFY_FINISHED_MSG";
	public static String CONFIG_KEY_JOB_DEFAULT_REPORT_MAIL_LIST = "CONFIG_KEY_JOB_DEFAULT_REPORT_MAIL_LIST";

	private static final long serialVersionUID = 1L;

	/**
	 * 配置项 CONFIGKEY
	 */
	@Id
	private String configkey;
	/**
	 * 配置值 CONFIGVALUE
	 */
	@Column(name = "CONFIGVALUE")
	private String configvalue;
	/**
	 * 描述 DESCRIPTION
	 */
	@Column(name = "DESCRIPTION")
	private String description;

	public String getConfigkey() {
		return this.configkey;
	}

	public void setConfigkey(String configkey) {
		this.configkey = configkey;
	}

	public String getConfigvalue() {
		return this.configvalue;
	}

	public String getShortConfigvalue() {
		if (configvalue != null && configvalue.getBytes().length > 40) {
			return bSubstring(configvalue, 39) + "...";
		}
		return this.configvalue;
	}

	public void setConfigvalue(String configvalue) {
		this.configvalue = configvalue;
	}

	public String getDescription() {
		return this.description;
	}

	public String getShortDescription() {
		if (description != null && description.getBytes().length > 40) {
			return bSubstring(description, 39) + "...";
		}
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
