/*
 * Copyright(C) 2010-2012 Alibaba Group Holding Limited
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License version 2 as
 *  published by the Free Software Foundation.
 *
 */
package com.taobao.ad.easyschedule.dataobject;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.taobao.ad.easyschedule.base.PageInfo;

/**
 * URescDO generated by hbm2java
 */
@Entity(name = "es_u_resc")
public class URescDO extends PageInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * ID
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
//	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "mseq")
//	@SequenceGenerator(name = "mseq", sequenceName = "SEQ_es_U_RESC", allocationSize = 1)
	private Long id;
	/**
	 * NAME
	 */
	@Column(name = "name")
	private String name;
	/**
	 * RES_TYPE
	 */
	@Column(name = "RES_TYPE")
	private String resType;
	/**
	 * RES_STRING
	 */
	@Column(name = "RES_STRING")
	private String resString;
	/**
	 * PRIORITY
	 */
	@Column(name = "PRIORITY")
	private Long priority;
	/**
	 * DESCN
	 */
	@Column(name = "DESCN")
	private String descn;
	/**
	 * CREATE_TIME
	 */
	@Column(name = "CREATE_TIME")
	private Date createTime;
	/**
	 * UPDATE_TIME
	 */
	@Column(name = "UPDATE_TIME")
	private Date updateTime;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getResType() {
		return this.resType;
	}

	public void setResType(String resType) {
		this.resType = resType;
	}

	public String getResString() {
		return this.resString;
	}

	public void setResString(String resString) {
		this.resString = resString;
	}

	public Long getPriority() {
		return this.priority;
	}

	public void setPriority(Long priority) {
		this.priority = priority;
	}

	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public URescDO() {
	}

//	public int hashCode() {
//		return this.hashCode();
//	}
//
//	public boolean equals(Object obj) {
//		return this.equals(obj);
//	}

}
