/*
 * Copyright(C) 2010-2012 Alibaba Group Holding Limited
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License version 2 as
 *  published by the Free Software Foundation.
 *
 */
package com.taobao.ad.easyschedule.dataobject;

// Generated 2010-10-3 15:14:15 by Hibernate Tools 3.2.4.GA 

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.taobao.ad.easyschedule.base.PageInfo;

/**
 * URoleDO generated by hbm2java
 */
@Entity(name = "es_u_role")
public class URoleDO extends PageInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * ID
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
//		@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "mseq")
//	@SequenceGenerator(name = "mseq", sequenceName = "SEQ_es_U_ROLE", allocationSize = 1)
	private Long id;
	/**
	 * NAME
	 */
	@Column(name = "name")
	private String name;
	/**
	 * DESCN
	 */
	@Column(name = "descn")
	private String descn;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	public URoleDO() {
	}


}
