/*
 * Copyright(C) 2010-2012 Alibaba Group Holding Limited
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License version 2 as
 *  published by the Free Software Foundation.
 *
 */
package com.taobao.ad.easyschedule.dataobject;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;

import com.taobao.ad.easyschedule.base.PageInfo;

/**
 * UUserDO generated by hbm2java
 */
@Entity(name = "es_u_user_role")
@IdClass(UserXReleKey.class)
public class UUserXRoleDO extends PageInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * userId
	 */
	@Id
	private Long userId;
	/**
	 * roleId
	 */
	@Id
	private Long roleId;

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getRoleId() {
		return roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public UUserXRoleDO() {
	}

	public int hashCode() {
		return this.hashCode();
	}

	public boolean equals(Object obj) {
		return this.equals(obj);
	}
}

@Embeddable
class UserXReleKey implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public UserXReleKey(){}
	@Column(name = "user_id")
	private Long userId;
	@Column(name = "role_id")
	private Long roleId;

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getRoleId() {
		return roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	 

}
